### ISSUE TITLE
Allow advanced network config for creating network (hurl new)

### ISSUE THREAD

**Issue by friendly-tech** [worldsibu/hurley#10]
Rather than just allowing number of channels, orgs, users etc.. allow an advanced option for creating a network - possibly based on a config file or config json passed on command line.

This could enable better control over how the network is built - controlling names and org<->channel relationships better.

For example
```

{
    "organizations": {
        "my-organization": {
            "channels": ["channel1", "channel2"],
            "peers": 3,
            "users": ["user1", "user2"]
        },
       "a-nother-org": {
            "channels": ["channel1"],
            "peers": 2,
            "users": ["user3", "user4"]
       }
    }
}
```

**Comment by walmon** [comment]
I can see that this ticket needs:

1. Allow for custom organization names
2. Allow for channels custom names
3. Allow adding organizations to specific channels
4. Allow custom amount of peers and independent peer count per organization
5. Allow for custom names of users
6. Allow custom count of users per organization

To be able to release something ASAP without much refactoring lets split them into:

- 1, 2, 5, and 6
- 3
- 4

As discussed on Discord I think that the first batch (1,2,5,6) can solve the spirit of the ticket. While the rest can be implemented later.
