### ISSUE TITLE
Cannot run on macOS: OCI runtime exec failed: exec failed: cannot exec a container that has stopped

### ISSUE THREAD

**Issue by cosmarc** [worldsibu/hurley#137]
When I'm trying to run `sudo hurl new` I get this error:
```
Creating ch1 channel block in peer peer0.org1.hurley.lab
OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown
cannot exec in a stopped state: unknown
Joining ch1 channel on peer peer0.org1.hurley.lab
++ docker exec peer0.org1.hurley.lab peer channel join -b /shared/ch1.block
Error response from daemon: Container 895b092811a5e276bb8122cdb632696c871b0a721242545723a710373213b1d4 is not running
```
I've tried to remove the `hyperledger-fabric-network` folder and run everything again but is still not working. 
Running on: 
macOS 10.15.2 (Catalina)
npm 5.6.0
ndoe 8.11.4

**Comment by diestrin** [comment]
You can do a `docker ps -a` and check out which container died (seems like it's the peer) and then checkout the container logs to see why

**Comment by cosmarc** [comment]
It happened because I was using sudo.
