### ISSUE TITLE
Hyperledger Explorer Support

### ISSUE THREAD

**Issue by aguel** [worldsibu/hurley#14]
Allows hurley to include provisioning of hyperledger explorer as optional parameter.

**Comment by walmon** [comment]
Hi @aguel thanks for your interest. Sadly this is out of the scope of Hurley, as Hurley is focused on provisioning a development environment, but I'm taking the note.

About your need to integrate with Hyperledger Explorer, we don't have a tutorial about it as usually connecting Explorer to Hurley becomes an overkill process (it just the development environment, maybe in production would make more sense).

However, if you'd like to explore your blocks we have successfully connected another project called Block Browser which is a much more lightweight OSS project incubated (or to be incubated) by the Linux foundation too - https://github.com/worldsibu/byzantine-browser here's our fork supporting TLS

You can find instructions on how to get it to work here: https://docs.worldsibu.com/article/92-explore-blocks

**Comment by walmon** [comment]
UPDATE: thanks to @aguel we now have a tutorial on how to use Hyperledger Explorer: https://docs.worldsibu.com/article/94-how-to-hyperledger-explorer
