### ISSUE TITLE
(node:112852) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by FilipLaurentiu** [worldsibu/hurley#143]
PS C:\Users\laurentiu.filip\Desktop\Test Convector> hurl --version
1.1.2
PS C:\Users\laurentiu.filip\Desktop\Test Convector> node -v
v8.1.0
PS C:\Users\laurentiu.filip\Desktop\Test Convector> hurl new
[hurley] - Hurley collects anonymous usage statistics to improve the tool over time
[hurley] - About to create binaries
[hurley] - Created and saved binaries
[hurley] - About to run binaries
[hurley] - Ran binaries
[hurley] - About to create configtxyaml
[hurley] - Created and saved configtxyaml
[hurley] - About to create cryptoconfigyaml
[hurley] - Created and saved cryptoconfigyaml
[hurley] - About to create cryptoconfigsh
[hurley] - Created and saved cryptoconfigsh
[hurley] - Running cryptoconfigsh
[hurley] - Ran cryptoconfigsh
[hurley] - Building compose
(node:112852) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'find' of undefined
(node:112852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I can't create a new fabric network. Any help ?

**Comment by diestrin** [comment]
This has been reported previously on #19. Sadly there's no fix for now, Hurley currently doesn't work on Windows.
