### ISSUE TITLE
Installling/instantiate chaincode on another channel

### ISSUE THREAD

**Issue by friendly-tech** [worldsibu/hurley#15]
Because of how hurl install works (it installs then instantiates on channel), you are not able to force instantiation on another channel due to the chaincode already being installed.

For example, the second install command will complain the chaincode already exists, but in reality you just want instantiation in that case.

```
hurl new -c 2

hurl install mychaincode node  -P ./chaincode-mychaincode

hurl install mychaincode node  -C ch2 -P  ./chaincode-mychaincode
```

Maybe install should accept array of channels to prevent need for subsequent calls.

**Comment by walmon** [comment]
https://github.com/worldsibu/hurley/tree/v1.0.3

https://github.com/worldsibu/hurley/commit/e67a63a8f51570df2632c4d060512e50b57a4c39
