### ISSUE TITLE
Join in an existing network

### ISSUE THREAD

**Issue by levanthanh3005** [worldsibu/hurley#205]
Hello,
I have a network created by hurley called network A,
Is this possbile to create an organization by hurley also from another machine and then join into network A,
I check hurley -h, and there is no function for that,
Thank for your time

**Comment by diestrin** [comment]
It is possible, but Hurley doesn't have any helpers to do that. Hurley creates the network and gives you all the private keys used, so you can send config transactions to manually update the network.
Remember Hurley is meant for development only, and that's why it doesn't have those tools.

**Comment by levanthanh3005** [comment]
thanks, I close the issue
