### ISSUE TITLE
docker-compose.yml generated is not friendly with Docker Swarm

### ISSUE THREAD

**Issue by hnarayanaswamy-rpx** [worldsibu/hurley#23]
The docker compose file generated by default supports only single node deployment. When we distribute the services across the swarm nodes things won't work because of failure in `hostname` / `service` resolution failure.

Two things need to be done to get it work on swarm as well as compose mode.

1. Give service name as normal DNS name component ( ie; name doesn't have "." in it )
2. Provide configured hostnames for each service as part of network alias.

I can sent PR for the same, if some alternate options are there please let me know.

**Comment by walmon** [comment]
Hi @hnarayanaswamy-rpx thanks for your message.

Absolutely, if you can drop a PR it's very welcomed! 

The community and contributors channel is in Discord in case you'd like to join and discuss further https://t.co/7MSSj4yo9o?amp=1

**Comment by hnarayanaswamy-rpx** [comment]
Sure @walmon Will send you a PR to make the orderer and orgs can be deployed on single node (via docker compose) or multi node using docker swarm.

Thanks for the channel link.

**Comment by haridas** [comment]
Sure @walmon Will send you a PR to make the orderer and orgs can be deployed on single node (via docker compose) or multi node using docker swarm.

Thanks for the channel link.

NOTE: I will be using this github account from here on.
