### ISSUE TITLE
Cannot pull image hyperledger/fabric-ccenv:latest

### ISSUE THREAD

**Issue by Merrick17** [worldsibu/hurley#265]
`Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:latest: API error (404): manifest for hyperledger/fabric-ccenv:latest not found: manifest unknown: manifest unknown`

when i run hurl install ..

**Comment by Merrick17** [comment]
any updates on this ?

**Comment by diestrin** [comment]
Hi @Merrick17 I've released Hurley v1.1.5 with a fix for this. Hyperledger removed the tag latest from docker, which was their default in 1.4. There was an env var we could pass to the peers specifying the image tag. Closed in #267
