### ISSUE TITLE
Error getting endorser client for channel while starting new blockchain network executing hurl new -o 3 command

### ISSUE THREAD

**Issue by gsolaich** [worldsibu/hurley#5]
While starting new blockchain network with 3 organizations using hurl command resulting in below error.
Error: error getting endorser client for channel: endorser client failed to connect to peer0.org1.hurley.lab:7051: failed to create new connection: context deadline exceeded

Node version - 8.11.1
NPM version - 5.6.0
OS - Ubuntu 16.04
<img width="1410" alt="screenshot 2019-01-14 at 6 01 25 am" src="https://user-images.githubusercontent.com/2004159/51127779-5f7b2d80-184c-11e9-8e00-164a6f04b9c4.png">

**Comment by walmon** [comment]
Hello. To diagnose better can you share the following information:

- Does it work when only creating 2 organizations? Or is the same issue?
- Run `npm list -g @worldsibu/hurley`. I see you ran `npm upgrade` at the end but sometimes internet connections may affect npm upgrading and results in silent failures.
- Finally, your docker version

I do have a similar environment to test this, so in the meantime that information above will be useful.

Thanks.

**Comment by walmon** [comment]
Hi @gsolaich I found the same issue on another Ubuntu setup, I pushed a fix for it (1a98fe05fa53d4a8dd3c470f351ebd51b784a4d9) and it's now released on 0.4.26
