### ISSUE TITLE
Can't install  in Ubuntu 

### ISSUE THREAD

**Issue by elohffa** [worldsibu/hurley#6]
I shoot a command in the terminal :  sudo npm i -g @worldsibu/hurley

it report a error , the  error message  is said 

/usr/local/bin/hurl -> /usr/local/lib/node_modules/@worldsibu/hurley/dist/command.js

> pkcs11js@1.0.17 install /usr/local/lib/node_modules/@worldsibu/hurley/node_modules/pkcs11js
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@worldsibu/hurley/node_modules/pkcs11js/build'
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@worldsibu/hurley/node_modules/pkcs11js
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pkcs11js@1.0.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pkcs11js@1.0.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/suntaiwai/.npm/_logs/2019-01-16T14_24_46_054Z-debug.log

**Comment by walmon** [comment]
That is a permissions issue, that depends on how you have configured your
computer.  It is common to require sudo for installation of global packages.

So `sudo npm ...` should do.

**Comment by walmon** [comment]
Sorry, I missed the `sudo` part. Maybe uninstall and reinstall? That doesn't look like a problem related to NPM nor Hurley.

**Comment by elohffa** [comment]
I use your command sudo npm install -g electron --unsafe-perm=true to install package , it look like fine , but when i sudo npm i -g @worldsibu/hurley , it report same error ..

**Comment by walmon** [comment]
Sorry, it was just a reference, what you have to actually run is

`sudo npm install -g @worldsibu/hurley --unsafe-perm=true`

**Comment by elohffa** [comment]
yes. I want to report , i use sudo npm i -g @worldsibu/hurley --unsafe-perm=true --allow-root , then the package can install without error

**Comment by elohffa** [comment]
Thanks for your help

**Comment by walmon** [comment]
Awesome! You are very welcome.

**Comment by insafachour** [comment]
hello
i have the same problem and i try your solution but i still having errors
