### ISSUE TITLE
Error when installing the chaincode on the network

### ISSUE THREAD

**Issue by lucianosilva44** [worldsibu/hurley#7]
Hello. My name is Luciano Campagnoli, and I am an intern at Brazilian Research Lab of IBM.
I was testing the new Hurley tool you have launched on the chanel WordSiBu with some templates in the Github repository mentioned in the Medium article of the channel. However, I'm having some problems here when instatiating the codechain in some examples (such as fabcar). When it turns to instantiate the code in the last node, Hurley launches an error: sometimes it claims an unexisting function init (and I do not find any call of it in the chaincode), or it spends minutes and minutes trying to make the instantiation and throws a timeout error. Do you imagine what could be happening?
It returns an error like that:
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg timeout expired while starting chaincode fabcar:1.0 for transaction

**Comment by lucianosilva44** [comment]
Note: I tried to install using the Javascript version of the chaincode.

**Comment by walmon** [comment]
Hi @lucianosilva44.

I'm looking into the fabcar chaincode and I see it requires some special constructor params, that is the reason why it is not instantiated correctly. 

Hurley exposes the `--ctor` parameter in case you want to include a custom constructor function other than the default one. If not specified, Hurley will default to `{"Args":["init",""]}` which doesn't exist in your chaincode.

This should get your installation working:

```
hurl install fabcar7 node --ctor '{"Args":[]}'
```

More information: https://github.com/worldsibu/hurley#hurl-install

Hope this help!

-----
Don't forget to join the chat https://discord.gg/twRwpWt

**Comment by lucianosilva44** [comment]
Thanks, @walmon. Now instantiated, I have another doubt: how could I interact with the chaincode on the network? Are there some APIs to operate with the sample of fabcar and the other ones?

**Comment by lucianosilva44** [comment]
For operations like adding a car, a customer, e.g

**Comment by walmon** [comment]
Yes, there are. All of them enter through Invoke. If you want to go low level you may call them directly. If not, you could use an SDK or if you want to try that example on Convector.

https://www.youtube.com/playlist?list=PL-1Vd1bTiSr_i2qeqeHCUWaD74ymRvidb
