### ISSUE TITLE
Error while trying to use hurl new command on Linux Mint

### ISSUE THREAD

**Issue by gargol12** [worldsibu/hurley#83]
I'm having this issue while trying to use "hurl new", I just finished installing convector using this guide -> https://docs.covalentx.com/article/120-install-on-ubuntu. I'm stuck in the last step.

Terminal log:
[hurley] - Hurley collects anonymous usage statistics to improve the tool over time
[hurley] - About to create binaries
[hurley] - Created and saved binaries
[hurley] - About to run binaries
Installing Hyperledger Fabric binaries
Binaries exist already
Checking IMAGES
===> Pulling fabric Images
==> FABRIC IMAGE: peer

1.4.0: Pulling from hyperledger/fabric-peer
Digest: sha256:9707c97f787de1d4d6dd60994d6b8ea2e5cc28b0f42e6849df3fb41c64b41372
Status: Image is up to date for hyperledger/fabric-peer:1.4.0
==> FABRIC IMAGE: orderer

1.4.0: Pulling from hyperledger/fabric-orderer
Digest: sha256:644265186b4887c7d9dcb91895124ccead3c0125c2c4f9eadc421dc9555d7495
Status: Image is up to date for hyperledger/fabric-orderer:1.4.0
==> FABRIC IMAGE: tools

1.4.0: Pulling from hyperledger/fabric-tools
Digest: sha256:aee256916d0cb938d8023fa32ed2745991d32cfe79018e360f1720707ebfbdb5
Status: Image is up to date for hyperledger/fabric-tools:1.4.0
===> Pulling fabric ca Image
==> FABRIC CA IMAGE

1.4.0: Pulling from hyperledger/fabric-ca
Digest: sha256:c1dce534d9e9202697e0aaad7c5521d958700fda0b05127dafb9333c22e15f74
Status: Image is up to date for hyperledger/fabric-ca:1.4.0
===> Pulling thirdparty docker images
==> THIRDPARTY DOCKER IMAGE: couchdb

0.4.14: Pulling from hyperledger/fabric-couchdb
Digest: sha256:021c7e4a5047432d892fbdf7d5220d3049ff4e8b436fd481bb08e41871f1aac7
Status: Image is up to date for hyperledger/fabric-couchdb:0.4.14

===> List out hyperledger docker images
[hurley] - Found error while running script!
(node:13369) UnhandledPromiseRejectionWarning: Error: Errors found in script, stopping execution
    at Object.<anonymous> (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/dist/utils/sysWrapper.js:116:27)
    at step (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:136:27)
    at Object.next (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:117:57)
    at /home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:106:16)
    at Object.execContent (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/dist/utils/sysWrapper.js:112:24)
    at DownloadFabricBinariesGenerator.BaseGenerator.run (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/dist/generators/base.js:18:40)
    at NetworkCLI.<anonymous> (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/dist/cli.js:191:53)
    at step (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:136:27)
(node:13369) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:13369) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by diestrin** [comment]
You should have a file `~/hyperledger-fabric-network/binaries.sh`, could you execute that script manually and check out what's the error it throws for you?

**Comment by gargol12** [comment]
thanks for the answer @diestrin, I executed the script manually and this was the output:
blockchain@smota93-MS-1454:~/hyperledger-fabric-network$ ./binaries.sh
Installing Hyperledger Fabric binaries
Binaries exist already
Checking IMAGES
===> Pulling fabric Images
==> FABRIC IMAGE: peer

1.4.0: Pulling from hyperledger/fabric-peer
Digest: sha256:9707c97f787de1d4d6dd60994d6b8ea2e5cc28b0f42e6849df3fb41c64b41372
Status: Image is up to date for hyperledger/fabric-peer:1.4.0
==> FABRIC IMAGE: orderer

1.4.0: Pulling from hyperledger/fabric-orderer
Digest: sha256:644265186b4887c7d9dcb91895124ccead3c0125c2c4f9eadc421dc9555d7495
Status: Image is up to date for hyperledger/fabric-orderer:1.4.0
==> FABRIC IMAGE: tools

1.4.0: Pulling from hyperledger/fabric-tools
Digest: sha256:aee256916d0cb938d8023fa32ed2745991d32cfe79018e360f1720707ebfbdb5
Status: Image is up to date for hyperledger/fabric-tools:1.4.0
===> Pulling fabric ca Image
==> FABRIC CA IMAGE

1.4.0: Pulling from hyperledger/fabric-ca
Digest: sha256:c1dce534d9e9202697e0aaad7c5521d958700fda0b05127dafb9333c22e15f74
Status: Image is up to date for hyperledger/fabric-ca:1.4.0
===> Pulling thirdparty docker images
==> THIRDPARTY DOCKER IMAGE: couchdb

0.4.14: Pulling from hyperledger/fabric-couchdb
Digest: sha256:021c7e4a5047432d892fbdf7d5220d3049ff4e8b436fd481bb08e41871f1aac7
Status: Image is up to date for hyperledger/fabric-couchdb:0.4.14

===> List out hyperledger docker images
hyperledger/fabric-ca          1.4.3               c18a0d3cc958        7 weeks ago         253MB
hyperledger/fabric-ca          1.4.1               3a1799cda5d7        6 months ago        252MB
hyperledger/fabric-tools       1.4.1               432c24764fbb        6 months ago        1.55GB
hyperledger/fabric-ccenv       1.4.1               d7433c4b2a1c        6 months ago        1.43GB
hyperledger/fabric-orderer     1.4.1               ec4ca236d3d4        6 months ago        173MB
hyperledger/fabric-peer        1.4.1               a1e3874f338b        6 months ago        178MB
hyperledger/fabric-zookeeper   0.4.15              20c6045930c8        7 months ago        1.43GB
hyperledger/fabric-zookeeper   latest              20c6045930c8        7 months ago        1.43GB
hyperledger/fabric-kafka       0.4.15              b4ab82bbaf2f        7 months ago        1.44GB
hyperledger/fabric-kafka       latest              b4ab82bbaf2f        7 months ago        1.44GB
hyperledger/fabric-couchdb     0.4.15              8de128a55539        7 months ago        1.5GB
hyperledger/fabric-javaenv     1.4.0               3d91b3bf7118        9 months ago        1.75GB
hyperledger/fabric-javaenv     latest              3d91b3bf7118        9 months ago        1.75GB
hyperledger/fabric-tools       1.4.0               0a44f4261a55        9 months ago        1.56GB
hyperledger/fabric-tools       latest              0a44f4261a55        9 months ago        1.56GB
hyperledger/fabric-ccenv       1.4.0               5b31d55f5f3a        9 months ago        1.43GB
hyperledger/fabric-ccenv       latest              5b31d55f5f3a        9 months ago        1.43GB
hyperledger/fabric-orderer     1.4.0               54f372205580        9 months ago        150MB
hyperledger/fabric-orderer     latest              54f372205580        9 months ago        150MB
hyperledger/fabric-peer        1.4.0               304fac59b501        9 months ago        157MB
hyperledger/fabric-peer        latest              304fac59b501        9 months ago        157MB
hyperledger/fabric-ca          1.4.0               1a804ab74f58        9 months ago        244MB
hyperledger/fabric-ca          latest              1a804ab74f58        9 months ago        244MB
hyperledger/fabric-couchdb     0.4.14              f14f97292b4c        12 months ago       1.5GB
hyperledger/fabric-couchdb     latest              f14f97292b4c        12 months ago       1.5GB
hyperledger/fabric-ccenv       1.2.1               8651e7160d88        12 months ago       1.43GB
hyperledger/fabric-orderer     1.2.1               b1a1dd788841        12 months ago       152MB
hyperledger/fabric-peer        1.2.1               ef0e7788ead0        12 months ago       159MB
hyperledger/fabric-ca          1.2.1               be8400395e15        12 months ago       251MB
hyperledger/fabric-zookeeper   0.4.10              2b51158f3898        15 months ago       1.44GB
hyperledger/fabric-kafka       0.4.10              936aef6db0e6        15 months ago       1.45GB
hyperledger/fabric-couchdb     0.4.10              3092eca241fc        15 months ago       1.61GB

after that I tried to do "hurl new" again but still shows the same issue.

===> List out hyperledger docker images
[hurley] - Found error while running script!
(node:18977) UnhandledPromiseRejectionWarning: Error: Errors found in script, stopping execution
    at Object.<anonymous> (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/dist/utils/sysWrapper.js:116:27)
    at step (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:136:27)
    at Object.next (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:117:57)
    at /home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:106:16)
    at Object.execContent (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/dist/utils/sysWrapper.js:112:24)
    at DownloadFabricBinariesGenerator.BaseGenerator.run (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/dist/generators/base.js:18:40)
    at NetworkCLI.<anonymous> (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/dist/cli.js:191:53)
    at step (/home/blockchain/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:136:27)
(node:18977) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:18977) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gargol12** [comment]
I just managed to solve the problem, seem like there was a problem with the docker version I got installed.
I fixed it reinstalling docker.io and docker-compose, removing the `hyperledger-fabric-network` folder and executing again the command `hurl new`.
Thanks to @diestrin for the quick answer, I can close this now.

**Comment by MicahMTurner** [comment]
@smota93 What Docker version worked for you? I'm having this same issue with Docker version 19.03.6, build 369ce74a3c

**Comment by smota93** [comment]
@MicahMTurner I used the lasted docker version at that moment.
