### ISSUE TITLE
Failed to install hurly in Fedora

### ISSUE THREAD

**Issue by jackyjqcheung** [worldsibu/hurley#93]
Hi guys,

When I tried to install hurley in Fedora linux, it encountered some error on step @ampretia/x509@0.4.0 install: `node-gyp rebuild`.

Here is the details.

OS:
Fedora release 30 (Thirty)
NAME=Fedora
nodejs: 8.11.4

Command:
npm i -g @worldsibu/hurley

Error:
npm WARN deprecated ts-simple-ast@11.3.0: NOTICE: ts-simple-ast has been renamed to ts-morph and version reset to 1.0.0. Switch at your leisure...
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
/home/peter/.nvm/versions/node/v8.11.4/bin/hurl -> /home/peter/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/dist/command.js

> @ampretia/x509@0.4.0 install /home/peter/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/@ampretia/x509
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/peter/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/peter/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/peter/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/peter/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/peter/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/peter/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 5.0.9-301.fc30.x86_64
gyp ERR! command "/home/peter/.nvm/versions/node/v8.11.4/bin/node" "/home/peter/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/peter/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/@ampretia/x509
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ampretia/x509@0.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ampretia/x509@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by diestrin** [comment]
Looks like your environment is missing some basic executables: `Error: not found: make`.

**Comment by jackyjqcheung** [comment]
You are right. After installing 
dnf install  make automake gcc gcc-c++ tar bzip2
It works well. Thanks.
